Update README + Add VIM temporary files to .gitignore
LearnTeachCode/code-coffee-compendium pull request #87
Opened 2021-08-11 04:36 UTC by TristanDamron

Satisfies the acceptance criteria for #80 and #81

2021-08-11 20:37 UTC, capsulecorplab requested changes

2021-08-11 20:37 UTC, capsulecorplab commented on README.adoc
> +sh build.sh
line isn't rendering as a code block. try 

```
[source]
----
sh build.sh
----
```

as per [callouts](https://gist.github.com/tracphil/87fff6ab2796fd855e62dd852eda502d#callouts) for GFA

2021-08-11 20:37 UTC, capsulecorplab commented on README.adoc
> +sudo sh build.sh
same issue as line 43

2021-08-11 20:37 UTC, capsulecorplab commented on README.adoc
> +sh serve.sh
same issue as line 43

2021-08-13 19:44 UTC, TristanDamron commented
@capsulecorplab Added another commit to address your concerns.

2021-08-13 21:03 UTC, capsulecorplab requested changes
Hm, still not rendering correctly https://github.com/LearnTeachCode/code-coffee-compendium/blob/b0afb5a3f9ffd1e10e396c67d6bb96a8b4073364/README.adoc

try adding another dash that's sandwiching the code snippet,
```
[source]
----
sh command
----
```

2021-08-25 03:25 UTC, TristanDamron commented
@capsulecorplab Updated my PR to fix the code blocks and to add a step for updating submodules if viewing the site locally!

2021-08-25 07:35 UTC, capsulecorplab approved these changes
___
                                     //   \\
                                    ||=====||
                                     \\___//
                                      ./O
                                  ___/ //|\\
                                 / o    /}
                                (       /
                                \      /
                                |     (
                                |      \
                                )       \
                               /         \
                             /            )
                           /              |
                         //             / /
                       /       ___(    ,| \
                     /       /    \     |  \
                    (      /  /   /\     \  \
                    \\   /___ _-_//'|     |  |
                     \\_______-/     \     \  \
                                      \-_-_-_-_-

                        "Seal of Approval"

2021-09-01 03:15 UTC, merged